# Generated by Django 6.1.1 on 2026-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('I', 'Iniciada'), ('C', 'Concluída')], default='P', max_length=1),
        ),
    ]
