# Generated by Django 6.1.1 on 2026-10-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_data_criacao_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'P'), ('Iniciada', 'I'), ('Concluída', 'C')], default='P', max_length=9),
        ),
    ]
