# Generated by Django 6.1.1 on 2026-10-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Iniciada', 'Iniciada'), ('Concluída', 'Concluída')], default='Pendente', max_length=9),
        ),
    ]
